fix(dual-list): set value to empty array when undefined
data-driven-forms/react-forms pull request #889
Opened 2020-11-16 12:07 UTC by boaz0

In dual list selector when the right side is empty, the value is set to undefined which causes that component to be discarded in the `values` object that is passed to `onSubmit`.

For example, I have three dual list selectors here:
![image](https://user-images.githubusercontent.com/2453279/99250616-a48b9480-2814-11eb-8f19-d298bdd6e1de.png)

If I click on "Submit", it will send an empty object {} as `values`.
With this patch it will send the following object:
```
{
 tags: {
  aws: { enabled: [] },
  azure: { enabled: [] },
  openshift: { enabled: [] }
 }
}
```

2020-11-16 12:09 UTC, Hyperkid123 commented
@boaz0 I am i correct to assume that this is an issue when sending data to some update API endpoint?

2020-11-16 12:46 UTC, Hyperkid123 requested changes
@boaz0 this is a breaking change for any other user of the dual list select component.

Can you check if [cleared value](https://data-driven-forms.org/schema/cleared-value#heading-clearedvalue) would help you instead?

If that is not the case, we would need some prop that to switch between the return value format.

2020-11-16 13:07 UTC, boaz0 commented
It won't work unless there is a way to pass that through `schema`.

2020-11-16 13:43 UTC, Hyperkid123 commented
@boaz0 you can use that config in schema directly. Or you can adjust the mapper and this prop globally specifically for the component via [global props](https://data-driven-forms.org/mappers/global-component-props#heading-globalcomponentprops).

2020-11-16 14:46 UTC, boaz0 commented
OK, so the problem is:
1) I want to set value to `[]` if is `undefined`.
2) my front end gets the schema from the backend and that means I cannot write a JS in my schema.
Maybe we can add a prop to dual-list-select to use empty array?

2020-11-16 22:15 UTC, closed without merging

2020-11-17 11:09 UTC, Hyperkid123 commented
@boaz0 did the cleared value prop worked?

2020-11-17 11:30 UTC, boaz0 commented
@Hyperkid123 yes it did. :+1: